name: Deploy on Vercel

on:
  push:
    branches:
      - production
  pull_request:
    branches:
      - production
  workflow_run:
    workflows: ['Hackathon Voting System Checks']
    types:
      - completed
jobs:
  main:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Push changes to deployment repository (production)
        run: |
          git remote add deployment https://github.com/DDuran19/castaway-voters
          git fetch deployment
          git push deployment production:production
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
